name: Generate Service Account Credential

on:
  workflow_dispatch:  # 支援手動執行

jobs:
  generate-credential:
    runs-on: ubuntu-latest

    steps:
      # 檢出程式碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 創建憑證文件
      - name: Create service account key file
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CREDENTIAL }}  # 從 Secrets 獲取 JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@example.com"
          git add ally-data01-95e5af44c537.json
          git commit -m "Add generated service account key"
          git push
